schema_version = "1.0.0"

id = "mcblend"
version = "0.3.1"
name = "Mcblend"
tagline = "A useful tool for creating minecraft content in blender"
maintainer = "Aspirata <Aspirata.minecraft@gmail.com>"
type = "add-on"

license = [
  "SPDX:GPL-2.0-or-later",
]

permissions = ["files"]

# Optional link to documentation, support, source files, etc
# website = "http://extensions.blender.org/add-ons/my-example-package/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Animation", "3D View", "Add Mesh", "Material"]

blender_version_min = "4.2.0"